### ISSUE TITLE
Calculate pxCov from binary file, not tiff files.

### ISSUE THREAD

**Issue by mjlm** [HarveyLab/Acquisition2P_class#6]
Should be much faster. Since the binary file is required for selectROIs now, we might as well use it for calcPxCov, too.

**Comment by Selmaan** [comment]
attempted this a while back, it actually seemed to be slower. I think this is because the algorithm we use to compute the covariances grabs pixel timeseries in a way that's inefficient from the .bin file. Without overhauling that, I think our current approach is faster
